name: Weekly cron

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  crds_contexts:
    uses: spacetelescope/crds/.github/workflows/contexts.yml@3e8ce9b857b90890ed31d0731d400344e17ccfb0  # 13.2.5
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@e5af21e4ae37af089a73bb032e10b78b0e746174  # v3.0.1
    needs: [ crds_contexts ]
    with:
      setenv: |
        CRDS_PATH: /tmp/data/crds_cache/
        CRDS_SERVER_URL: https://hst-crds.stsci.edu
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
      cache-path: /tmp/data/crds_cache/
      cache-key: ${{ needs.crds_contexts.outputs.hst }}
      libraries: |
        brew:
          - hdf5
      envs: |
        - linux: py3-devdeps-xdist
        - macos: py3-devdeps-xdist
      toxdeps: tox-uv
