name: Weekly cron

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  crds_contexts:
    uses: spacetelescope/crds/.github/workflows/contexts.yml@f48c5094926a9f0555e8352838a73371c1c4ec10  # 13.2.3
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@2835f0cacddf3f8de198db9afdb5354a5cebe0ef  # v2.6.3
    needs: [ crds_contexts ]
    with:
      setenv: |
        CRDS_PATH: /tmp/data/crds_cache/
        CRDS_SERVER_URL: https://hst-crds.stsci.edu
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
      cache-path: /tmp/data/crds_cache/
      cache-key: ${{ needs.crds_contexts.outputs.hst }}
      libraries: |
        brew:
          - hdf5
      envs: |
        - linux: py3-devdeps-xdist
        - macos: py3-devdeps-xdist
      toxdeps: tox-uv
